version: '3'

services:
  php.8-1:
    #image: php:8.1-fpm
    container_name: php.8-1
    working_dir: /var/www
    volumes:
      - ./:/var/www/
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"